# Generated by Django 3.2.9 on 2021-11-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='lienGithub',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
    ]
